repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: mise exec -- gitleaks git --pre-commit --redact --staged --verbose
        language: system
        pass_filenames: false
