#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<SQL
SELECT 'CREATE DATABASE ${BATCH_DB}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${BATCH_DB}')\gexec
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${BATCH_DB_USER}') THEN
    CREATE ROLE ${BATCH_DB_USER} LOGIN PASSWORD '${BATCH_DB_PASSWORD}';
  END IF;
END
\$\$;
GRANT ALL PRIVILEGES ON DATABASE ${BATCH_DB} TO ${BATCH_DB_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${BATCH_DB}" <<SQL
GRANT ALL ON SCHEMA public TO ${BATCH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${BATCH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${BATCH_DB_USER};
SQL
