deployments:
  webserver:
    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  executor:
    resources:
      requests:
        cpu: 200m
        memory: 768Mi
      limits:
        cpu: "1"
        memory: 1536Mi
  scheduler:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  indexer:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  worker:
    workerThreads: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    autoscaler:
      maxReplicas: 1
