apiVersion: v1
kind: Service
metadata:
  name: kestra-controller-grpc
  namespace: kestra
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kestra
    app.kubernetes.io/component: webserver
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
