apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kestra-podcreate
  namespace: kestra
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kestra-podcreate
  namespace: kestra
subjects:
  - kind: ServiceAccount
    name: kestra
    namespace: kestra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kestra-podcreate
